export const featuredProjects = [
  {
    title: 'xtarter',
    description: 'Home of my starter templates',
    featured: true,
    stacks: ['nextjs', 'chakra-ui'],
    date: '2022-05-19',
    projectLink: 'https://xtarter.sznm.dev',
    icon: '/app_icons/nextarter-chakra.svg',
    projectType: 'sites',
    body: { raw: '', html: '' },
    _id: 'projects/xtarter.md',
    _raw: {
      sourceFilePath: 'projects/xtarter.md',
      sourceFileName: 'xtarter.md',
      sourceFileDir: 'projects',
      contentType: 'markdown',
      flattenedPath: 'projects/xtarter',
    },
    type: 'Project',
    id: 'xtarter',
  },
  {
    title: 'wussh',
    description: 'Create personalized link page.',
    highlight: true,
    featured: true,
    sznmApps: true,
    stacks: ['nextjs', 'chakra-ui'],
    date: '2021-05-07',
    projectLink: 'https://wussh.sznm.dev',
    icon: '/app_icons/link.svg',
    thumbnail: '/app_preview/wussh.png',
    projectType: 'apps',
    body: { raw: '', html: '' },
    _id: 'projects/wussh.md',
    _raw: {
      sourceFilePath: 'projects/wussh.md',
      sourceFileName: 'wussh.md',
      sourceFileDir: 'projects',
      contentType: 'markdown',
      flattenedPath: 'projects/wussh',
    },
    type: 'Project',
    id: 'wussh',
  },
  {
    title: 'spoker',
    description: 'My take on scrum poker.',
    highlight: true,
    featured: true,
    sznmApps: true,
    stacks: ['nextjs', 'chakra-ui'],
    date: '2021-02-28',
    projectLink: 'https://spoker.dev/intro',
    icon: '/app_icons/chip.svg',
    thumbnail: '/app_preview/spoker.png',
    projectType: 'apps',
    body: { raw: '', html: '' },
    _id: 'projects/spoker.md',
    _raw: {
      sourceFilePath: 'projects/spoker.md',
      sourceFileName: 'spoker.md',
      sourceFileDir: 'projects',
      contentType: 'markdown',
      flattenedPath: 'projects/spoker',
    },
    type: 'Project',
    id: 'spoker',
  },
  {
    title: 'Greetings as a Service (GaaS)',
    description: 'Make personalized greetings message for your folks.',
    featured: true,
    sznmApps: true,
    stacks: ['nextjs', 'chakra-ui'],
    date: '2021-01-01',
    projectLink: 'https://gaas.sznm.dev/',
    icon: '/app_icons/greet-gaas.svg',
    thumbnail: '/app_preview/gaas.png',
    thumbnailDark: '/app_preview/gaas-dark.png',
    projectType: 'apps',
    body: { raw: '', html: '' },
    _id: 'projects/greet-gaas.md',
    _raw: {
      sourceFilePath: 'projects/greet-gaas.md',
      sourceFileName: 'greet-gaas.md',
      sourceFileDir: 'projects',
      contentType: 'markdown',
      flattenedPath: 'projects/greet-gaas',
    },
    type: 'Project',
    id: 'greet-gaas',
  },
  {
    title: 'muvees',
    description: 'Just another movie DB app',
    featured: true,
    sznmApps: true,
    stacks: ['nextjs', 'chakra-ui'],
    date: '2020-12-29',
    projectLink: 'https://muvees.sznm.dev',
    icon: '/app_icons/popcorn.png',
    projectType: 'sites',
    body: { raw: '', html: '' },
    _id: 'projects/muvees.md',
    _raw: {
      sourceFilePath: 'projects/muvees.md',
      sourceFileName: 'muvees.md',
      sourceFileDir: 'projects',
      contentType: 'markdown',
      flattenedPath: 'projects/muvees',
    },
    type: 'Project',
    id: 'muvees',
  },
  {
    title: 'Public APIs',
    description: 'Find public APIs for your next projects.',
    featured: true,
    sznmApps: true,
    stacks: ['nextjs', 'chakra-ui'],
    date: '2020-12-25',
    projectLink: 'https://publicapis.sznm.dev',
    repoLink: 'https://github.com/sozonome/pub-apis',
    icon: '/app_icons/pub-apis.svg',
    thumbnail: '/app_preview/public-apis.png',
    thumbnailDark: '/app_preview/public-apis-dark.png',
    projectType: 'apps',
    body: { raw: '', html: '' },
    _id: 'projects/pub-apis.md',
    _raw: {
      sourceFilePath: 'projects/pub-apis.md',
      sourceFileName: 'pub-apis.md',
      sourceFileDir: 'projects',
      contentType: 'markdown',
      flattenedPath: 'projects/pub-apis',
    },
    type: 'Project',
    id: 'pub-apis',
  },
]
