import type { Metadata } from 'next'
import './globals.css'
import Layout from '@/components/layout'
import { Outfit as FontHeading, Geologica as FontBody } from 'next/font/google'
import { cn } from '@/lib/utils'

const fontHeading = FontHeading({
  subsets: ['latin'],
  variable: '--font-heading',
})

const fontBody = FontBody({
  subsets: ['latin'],
  variable: '--font-body',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn(fontBody.variable, fontHeading.variable)}>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
